swagger: "2.0"

info:
  title: "{{title}}"
  version: "0.0.5"

basePath: /eds

paths:
  /devices:
    get:
      #operationId: eds.get_all
      summary: Get all devices
      parameters:
       - in: query
         name: servicename
         type: string
         enum: ["ZigBeeIPE", "MemsIPE"]
         description: "Enter sensor service name here."
         required: true

       - in: query
         name: id
         type: string
         description: "Enter sensor device ID here."
         required: true
      responses:
        '200':
          description: 'Fetch a list of devices'
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'


  '/devices/{id}':
    put:
     # operationId: eds.put
      summary: Create or update a device
      parameters:
        - in: body
          name: servicename
          required: true
          schema:
            $ref: '#/definitions/Device'
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: 'Update a device by ID'
    delete:
     # operationId: eds.delete
      summary: delete a divce by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string

      responses:
        '204':
          description: 'Delete a device by device id'
    get:
      #operationId: eds.get
      summary: Get one specific Device infor
      parameters:
        - in: path
          name: id
          required: true
          type: string

        - in: query
          name: servicename
          type: string
          enum: ["ZigBeeIPE", "MemsIPE"]
          description: "Enter sensor service name here."
          required: true
      responses:
        '200':
          description: 'Fetch a device by ID'
          schema:
            $ref: '#/definitions/Device'
definitions:
 Device:
    type: object
    properties:
      servicename:
       type: string
       pattern: "^[a-zA-Z0-9]*$"
      id:
       type: string
       pattern: "^[a-zA-Z0-9]*$"
      mems:
        $ref: '#/definitions/Mems'

      registered:
        type: string
        format: date-time




 Mems:
    type: object
    properties:
        id:
          type: string
          example: "Mem01"
        axis:
          type: object
          properties:
            x:
             $ref: '#/definitions/X'
            y:
             $ref: '#/definitions/Y'
            z:
             $ref: '#/definitions/Z'

 X:
      type: object
      properties:
        bn:
          type: string
          example: "urn:dev1:memsipe"
          description: "basename of the mems sensor"

        u:
          type: string
          example: "g"
        v:
          type: number
          format: float
        t:
          type: string
          format: date-time
          description: the timestamp when the brightness was measured
        n:
          type: string
          example: "x"

        lbl:
          type: string
          example: "openmtc:sensor_data"
      description: ok


 Y:
      type: object
      properties:
        bn:
          type: string
          example: "urn:dev1:memsipe"
          description: "basename of the mems sensor"

        u:
          type: string
          example: "g"
        v:
          type: number
          format: float
        t:
          type: string
          format: date-time
          description: the timestamp when the brightness was measured
        n:
          type: string
          example: "y"

        lbl:
          type: string
          example: "openmtc:sensor_data"
      description: ok

 Z:
      type: object
      properties:
        bn:
          type: string
          example: "urn:dev1:memsipe"
          description: "basename of the mems sensor"

        u:
          type: string
          example: "g"
        v:
          type: number
          format: float
        t:
          type: string
          format: date-time
          description: the timestamp when the brightness was measured
        n:
          type: string
          example: "z"

        lbl:
          type: string
          example: "openmtc:sensor_data"
      description: ok




