# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DeviceRegistrationInfo(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, uri=None, device_name=None):
        """
        DeviceRegistrationInfo - a model defined in Swagger

        :param uri: The uri of this DeviceRegistrationInfo.
        :type uri: str
        :param device_name: The device_name of this DeviceRegistrationInfo.
        :type device_name: str
        """
        self.swagger_types = {
            'uri': str,
            'device_name': str
        }

        self.attribute_map = {
            'uri': 'uri',
            'device_name': 'deviceName'
        }

        self._uri = uri
        self._device_name = device_name

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeviceRegistrationInfo of this DeviceRegistrationInfo.
        :rtype: DeviceRegistrationInfo
        """
        return deserialize_model(dikt, cls)

    @property
    def uri(self):
        """
        Gets the uri of this DeviceRegistrationInfo.

        :return: The uri of this DeviceRegistrationInfo.
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """
        Sets the uri of this DeviceRegistrationInfo.

        :param uri: The uri of this DeviceRegistrationInfo.
        :type uri: str
        """

        self._uri = uri

    @property
    def device_name(self):
        """
        Gets the device_name of this DeviceRegistrationInfo.

        :return: The device_name of this DeviceRegistrationInfo.
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """
        Sets the device_name of this DeviceRegistrationInfo.

        :param device_name: The device_name of this DeviceRegistrationInfo.
        :type device_name: str
        """

        self._device_name = device_name

