# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Humidity(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, nm=None, u=None, v=None, t=None, n=None, lbl=None):
        """
        Humidity - a model defined in Swagger

        :param nm: The nm of this Humidity.
        :type nm: str
        :param u: The u of this Humidity.
        :type u: str
        :param v: The v of this Humidity.
        :type v: float
        :param t: The t of this Humidity.
        :type t: datetime
        :param n: The n of this Humidity.
        :type n: str
        :param lbl: The lbl of this Humidity.
        :type lbl: str
        """
        self.swagger_types = {
            'nm': str,
            'u': str,
            'v': float,
            't': datetime,
            'n': str,
            'lbl': str
        }

        self.attribute_map = {
            'nm': 'nm',
            'u': 'u',
            'v': 'v',
            't': 't',
            'n': 'n',
            'lbl': 'lbl'
        }

        self._nm = nm
        self._u = u
        self._v = v
        self._t = t
        self._n = n
        self._lbl = lbl

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Humidity of this Humidity.
        :rtype: Humidity
        """
        return deserialize_model(dikt, cls)

    @property
    def nm(self):
        """
        Gets the nm of this Humidity.

        :return: The nm of this Humidity.
        :rtype: str
        """
        return self._nm

    @nm.setter
    def nm(self, nm):
        """
        Sets the nm of this Humidity.

        :param nm: The nm of this Humidity.
        :type nm: str
        """
        allowed_values = ["ZBS122S000001", "ZBS122S000000"]
        if nm not in allowed_values:
            raise ValueError(
                "Invalid value for `nm` ({0}), must be one of {1}"
                .format(nm, allowed_values)
            )

        self._nm = nm

    @property
    def u(self):
        """
        Gets the u of this Humidity.

        :return: The u of this Humidity.
        :rtype: str
        """
        return self._u

    @u.setter
    def u(self, u):
        """
        Sets the u of this Humidity.

        :param u: The u of this Humidity.
        :type u: str
        """

        self._u = u

    @property
    def v(self):
        """
        Gets the v of this Humidity.

        :return: The v of this Humidity.
        :rtype: float
        """
        return self._v

    @v.setter
    def v(self, v):
        """
        Sets the v of this Humidity.

        :param v: The v of this Humidity.
        :type v: float
        """

        self._v = v

    @property
    def t(self):
        """
        Gets the t of this Humidity.
        the timestamp when the brightness was measured

        :return: The t of this Humidity.
        :rtype: datetime
        """
        return self._t

    @t.setter
    def t(self, t):
        """
        Sets the t of this Humidity.
        the timestamp when the brightness was measured

        :param t: The t of this Humidity.
        :type t: datetime
        """

        self._t = t

    @property
    def n(self):
        """
        Gets the n of this Humidity.

        :return: The n of this Humidity.
        :rtype: str
        """
        return self._n

    @n.setter
    def n(self, n):
        """
        Sets the n of this Humidity.

        :param n: The n of this Humidity.
        :type n: str
        """

        self._n = n

    @property
    def lbl(self):
        """
        Gets the lbl of this Humidity.

        :return: The lbl of this Humidity.
        :rtype: str
        """
        return self._lbl

    @lbl.setter
    def lbl(self, lbl):
        """
        Sets the lbl of this Humidity.

        :param lbl: The lbl of this Humidity.
        :type lbl: str
        """

        self._lbl = lbl

