# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.x import X
from swagger_server.models.y import Y
from swagger_server.models.z import Z
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class MemsData(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, x=None, y=None, z=None):
        """
        MemsData - a model defined in Swagger

        :param x: The x of this MemsData.
        :type x: X
        :param y: The y of this MemsData.
        :type y: Y
        :param z: The z of this MemsData.
        :type z: Z
        """
        self.swagger_types = {
            'x': X,
            'y': Y,
            'z': Z
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'z': 'z'
        }

        self._x = x
        self._y = y
        self._z = z

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MemsData of this MemsData.
        :rtype: MemsData
        """
        return deserialize_model(dikt, cls)

    @property
    def x(self):
        """
        Gets the x of this MemsData.

        :return: The x of this MemsData.
        :rtype: X
        """
        return self._x

    @x.setter
    def x(self, x):
        """
        Sets the x of this MemsData.

        :param x: The x of this MemsData.
        :type x: X
        """

        self._x = x

    @property
    def y(self):
        """
        Gets the y of this MemsData.

        :return: The y of this MemsData.
        :rtype: Y
        """
        return self._y

    @y.setter
    def y(self, y):
        """
        Sets the y of this MemsData.

        :param y: The y of this MemsData.
        :type y: Y
        """

        self._y = y

    @property
    def z(self):
        """
        Gets the z of this MemsData.

        :return: The z of this MemsData.
        :rtype: Z
        """
        return self._z

    @z.setter
    def z(self, z):
        """
        Sets the z of this MemsData.

        :param z: The z of this MemsData.
        :type z: Z
        """

        self._z = z

