# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class X(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, bn=None, u=None, v=None, t=None, n=None, lbl=None):
        """
        X - a model defined in Swagger

        :param bn: The bn of this X.
        :type bn: str
        :param u: The u of this X.
        :type u: str
        :param v: The v of this X.
        :type v: float
        :param t: The t of this X.
        :type t: datetime
        :param n: The n of this X.
        :type n: str
        :param lbl: The lbl of this X.
        :type lbl: str
        """
        self.swagger_types = {
            'bn': str,
            'u': str,
            'v': float,
            't': datetime,
            'n': str,
            'lbl': str
        }

        self.attribute_map = {
            'bn': 'bn',
            'u': 'u',
            'v': 'v',
            't': 't',
            'n': 'n',
            'lbl': 'lbl'
        }

        self._bn = bn
        self._u = u
        self._v = v
        self._t = t
        self._n = n
        self._lbl = lbl

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The X of this X.
        :rtype: X
        """
        return deserialize_model(dikt, cls)

    @property
    def bn(self):
        """
        Gets the bn of this X.
        basename of the mems sensor

        :return: The bn of this X.
        :rtype: str
        """
        return self._bn

    @bn.setter
    def bn(self, bn):
        """
        Sets the bn of this X.
        basename of the mems sensor

        :param bn: The bn of this X.
        :type bn: str
        """

        self._bn = bn

    @property
    def u(self):
        """
        Gets the u of this X.

        :return: The u of this X.
        :rtype: str
        """
        return self._u

    @u.setter
    def u(self, u):
        """
        Sets the u of this X.

        :param u: The u of this X.
        :type u: str
        """

        self._u = u

    @property
    def v(self):
        """
        Gets the v of this X.

        :return: The v of this X.
        :rtype: float
        """
        return self._v

    @v.setter
    def v(self, v):
        """
        Sets the v of this X.

        :param v: The v of this X.
        :type v: float
        """

        self._v = v

    @property
    def t(self):
        """
        Gets the t of this X.
        the timestamp when the brightness was measured

        :return: The t of this X.
        :rtype: datetime
        """
        return self._t

    @t.setter
    def t(self, t):
        """
        Sets the t of this X.
        the timestamp when the brightness was measured

        :param t: The t of this X.
        :type t: datetime
        """

        self._t = t

    @property
    def n(self):
        """
        Gets the n of this X.

        :return: The n of this X.
        :rtype: str
        """
        return self._n

    @n.setter
    def n(self, n):
        """
        Sets the n of this X.

        :param n: The n of this X.
        :type n: str
        """

        self._n = n

    @property
    def lbl(self):
        """
        Gets the lbl of this X.

        :return: The lbl of this X.
        :rtype: str
        """
        return self._lbl

    @lbl.setter
    def lbl(self, lbl):
        """
        Sets the lbl of this X.

        :param lbl: The lbl of this X.
        :type lbl: str
        """

        self._lbl = lbl

